CREATE DATABASE IF NOT EXISTS bukutamu;
USE bukutamu;

CREATE TABLE tamu (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    pesan TEXT NOT NULL,
    waktu TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip VARCHAR(45) NOT NULL,
    user_agent TEXT NOT NULL,
	email VARCHAR(100),
	website VARCHAR(100),
	genre ENUM('male', 'female') DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
