CREATE DATABASE IF NOT EXISTS bukutamu;
USE bukutamu;

CREATE TABLE tamu (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    pesan TEXT NOT NULL,
    waktu TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip VARCHAR(45) NOT NULL,
    user_agent TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
